version: '3.9'

services:
  app:
    build: .
    container_name: catalystcare_be

    restart: always

    ports:
      - "4000:4000"

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

    command: sh -c "npx prisma migrate deploy && npm run start"

  worker:
    build: .

    container_name: catalystcare_worker

    restart: always

    env_file:
      - .env

    depends_on:
      - postgres
      - redis

    command: sh -c "npm run start:workers"

  postgres:
    image: postgres:16

    container_name: catalystcare_postgres

    restart: always

    environment:
      POSTGRES_USER: devappuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: catalystcaredb

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2

    container_name: redis_server

    restart: always

    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
